# Generated by Django 6.0.2 on 2026-02-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
