# Generated by Django 6.0.2 on 2026-02-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_sellers_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellers',
            name='is_active',
        ),
        migrations.AddField(
            model_name='sellers',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
