# Generated by Django 6.0.2 on 2026-02-19 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_sellers_is_active_sellers_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('expiry', models.DateField(null=True)),
                ('category', models.CharField(max_length=120)),
                ('image', models.ImageField(null=True, upload_to='products')),
                ('is_deleted', models.BooleanField(default=False)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.sellers')),
            ],
        ),
    ]
