# Generated by Django 6.0.2 on 2026-02-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
