# Generated by Django 6.0.2 on 2026-02-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_seller_id_products_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='products'),
        ),
    ]
