# Generated by Django 6.0.2 on 2026-02-23 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitems_price_at_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='type',
            new_name='order_type',
        ),
    ]
